# Generated by Django 5.2 on 2025-04-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='can_manage_blogs',
        ),
    ]
