# Generated by Django 5.1 on 2025-04-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
