# Generated by Django 5.2 on 2025-07-10 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('admissions', '0001_initial'),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSemesterEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, help_text='The date and time this enrollment was recorded.')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='enrolled', help_text='Select the status of this semester enrollment.', max_length=20)),
            ],
            options={
                'verbose_name': 'Student Semester Enrollment',
                'verbose_name_plural': 'Student Semester Enrollments',
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, help_text='The date and time this course enrollment was recorded.')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='enrolled', help_text='Select the status of this course enrollment.', max_length=20)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.courseoffering')),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('applicant', models.OneToOneField(help_text='Select the applicant record associated with this student.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to='admissions.applicant')),
                ('university_roll_no', models.IntegerField(blank=True, help_text="Enter the student's official university roll number.", null=True)),
                ('college_roll_no', models.IntegerField(blank=True, help_text="Enter the student's college roll number (if applicable).", null=True)),
                ('enrollment_date', models.DateField(help_text='Select the official date when the student was enrolled.')),
                ('graduation_date', models.DateField(blank=True, help_text='Select the date when the student graduated (optional).', null=True)),
                ('current_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn')], default='active', help_text='Select the current academic status of the student.', max_length=20)),
                ('emergency_contact', models.CharField(blank=True, help_text='Enter the name of an emergency contact person.', max_length=100)),
                ('emergency_phone', models.CharField(blank=True, help_text='Enter the phone number for the emergency contact.', max_length=15)),
                ('role', models.CharField(blank=True, choices=[('CR', 'Class Representative'), ('GR', 'Girls Representative')], help_text="Select the student's role (CR/GR) if applicable.", max_length=2, null=True)),
                ('program', models.ForeignKey(help_text='The program the student is enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.program')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
