# Generated by Django 5.2 on 2025-05-23 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('courses', '0002_alter_courseoffering_academic_session_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_semester',
            field=models.ForeignKey(default=1, help_text='Current semester of the student', on_delete=django.db.models.deletion.PROTECT, related_name='current_students', to='courses.semester'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.ForeignKey(default=1, help_text='The program the student is enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.program'),
            preserve_default=False,
        ),
    ]
