# Generated by Django 5.2 on 2025-07-10 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Select the user account linked to this student profile (optional, automatically linked if available).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentsemesterenrollment',
            name='semester',
            field=models.ForeignKey(help_text='Select the semester the student is enrolling in.', on_delete=django.db.models.deletion.CASCADE, related_name='semester_enrollments', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='studentsemesterenrollment',
            name='student',
            field=models.ForeignKey(help_text='Select the student for this semester enrollment.', on_delete=django.db.models.deletion.CASCADE, related_name='semester_enrollments', to='students.student'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='student_semester_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='students.studentsemesterenrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='studentsemesterenrollment',
            unique_together={('student', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('student_semester_enrollment', 'course_offering')},
        ),
    ]
