# Generated by Django 5.2 on 2025-07-16 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_staff', '0004_departmentfund_fundtype'),
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFundPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partially Paid')], default='pending', help_text='Payment status for this fund', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, help_text='Amount paid by the student', max_digits=10)),
                ('payment_date', models.DateTimeField(blank=True, help_text='When the payment was made', null=True)),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about the payment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_payments', to='faculty_staff.departmentfund')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_payments', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Fund Payment',
                'verbose_name_plural': 'Student Fund Payments',
                'unique_together': {('student', 'fund')},
            },
        ),
    ]
