# Generated by Django 5.2 on 2025-06-22 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_semester',
        ),
    ]
