# Generated by Django 5.2 on 2025-05-25 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_studentgrade_grade_and_more'),
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_semester',
            field=models.ForeignKey(help_text='Current semester of the student', on_delete=django.db.models.deletion.PROTECT, related_name='current_students', to='academics.semester'),
        ),
    ]
