# Generated by Django 5.2 on 2025-07-16 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentfundpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfundpayment',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Student who verified this payment (CR/GR)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to='students.student'),
        ),
    ]
