# Generated by Django 5.2 on 2025-05-25 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_semester_options_and_more'),
        ('students', '0003_alter_student_current_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSemesterEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, help_text='The date and time this enrollment was recorded.')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='enrolled', help_text='Select the status of this semester enrollment.', max_length=20)),
                ('semester', models.ForeignKey(help_text='Select the semester the student is enrolling in.', on_delete=django.db.models.deletion.CASCADE, related_name='semester_enrollments', to='academics.semester')),
                ('student', models.ForeignKey(help_text='Select the student for this semester enrollment.', on_delete=django.db.models.deletion.CASCADE, related_name='semester_enrollments', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Semester Enrollment',
                'verbose_name_plural': 'Student Semester Enrollments',
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.DeleteModel(
            name='StudentEnrollment',
        ),
    ]
