# Generated by Django 5.2 on 2025-07-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_current_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(blank=True, choices=[('CR', 'Class Representative'), ('GR', 'Girls Representative')], help_text="Select the student's role (CR/GR) if applicable.", max_length=2, null=True),
        ),
    ]
