# Generated by Django 5.2 on 2025-07-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_studentfundpayment_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfundpayment',
            name='proof',
            field=models.FileField(blank=True, help_text='Upload proof of payment (PDF, JPG, or PNG)', null=True, upload_to='payment_proofs/%Y/%m/%d/'),
        ),
    ]
