# Generated by Django 5.2.3 on 2025-07-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingsEncode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(help_text='Academic session (e.g., 2022-2026)', max_length=50)),
                ('program', models.CharField(help_text='Program name (e.g., BSCS)', max_length=50)),
                ('shift', models.CharField(choices=[('Morning', 'morning'), ('Evening', 'evening')], default='Morning', help_text='Shift of the program (e.g., Morning, Evening)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation')),
            ],
            options={
                'verbose_name': 'Embedding Encode',
                'verbose_name_plural': 'Embedding Encodes',
                'indexes': [models.Index(fields=['session', 'program', 'shift'], name='students_em_session_76207c_idx')],
            },
        ),
    ]
