# Generated by Django 5.2 on 2025-05-26 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_courseoffering_current_enrollment_and_more'),
        ('students', '0004_studentsemesterenrollment_delete_studentenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsemesterenrollment',
            name='course_offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.courseoffering'),
        ),
    ]
