# Generated by Django 5.2 on 2025-05-26 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentsemesterenrollment_course_offering'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsemesterenrollment',
            unique_together=set(),
        ),
    ]
