# Generated by Django 5.2.3 on 2025-07-11 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_embeddingsencode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic', models.CharField(help_text='Unique CNIC of the student (e.g., 12345-6789012-3)', max_length=15)),
                ('embeddings', models.BinaryField(help_text='Serialized face embedding data')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
                ('ecode', models.ForeignKey(help_text='Reference to EmbeddingsEncode record', on_delete=django.db.models.deletion.CASCADE, to='students.embeddingsencode')),
            ],
            options={
                'verbose_name': 'Face Embedding',
                'verbose_name_plural': 'Face Embeddings',
                'indexes': [models.Index(fields=['ecode', 'cnic'], name='students_fa_ecode_i_5c7854_idx')],
            },
        ),
    ]
