# Generated by Django 5.2 on 2025-07-20 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentfundpayment_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Registration_number',
            field=models.CharField(blank=True, help_text="Enter the student's unique registration number.", max_length=20, null=True, unique=True),
        ),
    ]
