# Generated by Django 5.2.4 on 2025-07-25 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentfundpayment_proof'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingsEncode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(help_text='Academic session (e.g., 2022-2026)', max_length=50)),
                ('program', models.CharField(help_text='Program name (e.g., BSCS)', max_length=50)),
                ('shift', models.CharField(choices=[('Morning', 'morning'), ('Evening', 'evening')], default='Morning', help_text='Shift of the program (e.g., Morning, Evening)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation')),
            ],
            options={
                'verbose_name': 'Embedding Encode',
                'verbose_name_plural': 'Embedding Encodes',
                'indexes': [models.Index(fields=['session', 'program', 'shift'], name='students_em_session_76207c_idx')],
            },
        ),
        migrations.CreateModel(
            name='FaceEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic', models.CharField(help_text='Unique CNIC of the student (e.g., 12345-6789012-3)', max_length=15)),
                ('embeddings', models.BinaryField(help_text='Serialized face embedding data')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp of last update')),
                ('ecode', models.ForeignKey(help_text='Reference to EmbeddingsEncode record', on_delete=django.db.models.deletion.CASCADE, to='students.embeddingsencode')),
            ],
            options={
                'verbose_name': 'Face Embedding',
                'verbose_name_plural': 'Face Embeddings',
                'indexes': [models.Index(fields=['ecode', 'cnic'], name='students_fa_ecode_i_5c7854_idx')],
            },
        ),
    ]
