# Generated by Django 5.2.3 on 2025-07-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_faceembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Registration_number',
            field=models.CharField(blank=True, help_text="Enter the student's unique registration number (e.g., 2023-CS-001).", null=True, unique=True),
        ),
    ]
