# Generated by Django 5.2 on 2025-05-26 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_semester_options_and_more'),
        ('courses', '0005_remove_courseoffering_current_enrollment_and_more'),
        ('students', '0006_alter_studentsemesterenrollment_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentsemesterenrollment',
            unique_together={('student', 'semester')},
        ),
        migrations.RemoveField(
            model_name='studentsemesterenrollment',
            name='course_offering',
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField(auto_now_add=True, help_text='The date and time this course enrollment was recorded.')),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='enrolled', help_text='Select the status of this course enrollment.', max_length=20)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.courseoffering')),
                ('student_semester_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='students.studentsemesterenrollment')),
            ],
            options={
                'verbose_name': 'Course Enrollment',
                'verbose_name_plural': 'Course Enrollments',
                'unique_together': {('student_semester_enrollment', 'course_offering')},
            },
        ),
    ]
