# Generated by Django 5.2 on 2025-07-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='is_repeat',
            field=models.BooleanField(default=False, help_text='Indicates if this is a repeat enrollment in the course.'),
        ),
    ]
