# Generated by Django 5.2.4 on 2025-07-27 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_courseenrollment_is_repeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_roll_no', models.IntegerField(help_text="The student's university roll number.")),
                ('embedding_data', models.BinaryField(help_text='Serialized NumPy face embedding data')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this embedding was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this embedding was last updated')),
                ('student', models.ForeignKey(help_text='Reference to the associated student', on_delete=django.db.models.deletion.CASCADE, related_name='face_embeddings', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Embedding',
                'verbose_name_plural': 'Student Embeddings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student'], name='students_st_student_aa98be_idx')],
            },
        ),
    ]
