# Generated by Django 5.2.3 on 2025-07-17 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_registration_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
