# Generated by Django 5.2 on 2025-05-17 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_start', models.DateField()),
                ('application_end', models.DateField()),
                ('is_open', models.BooleanField(default=False)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.program')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.academicsession')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant_photo', models.ImageField(blank=True, upload_to='photos/')),
                ('full_name', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('cnic', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('contact_no', models.CharField(max_length=15)),
                ('identification_mark', models.TextField(blank=True)),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(max_length=100)),
                ('father_cnic', models.CharField(max_length=15)),
                ('monthly_income', models.PositiveIntegerField()),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('guardian', 'Guardian')], max_length=50)),
                ('permanent_address', models.TextField()),
                ('declaration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.faculty')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_passed', models.CharField(max_length=100)),
                ('passing_year', models.PositiveIntegerField()),
                ('marks_obtained', models.PositiveIntegerField()),
                ('total_marks', models.PositiveIntegerField()),
                ('division', models.CharField(max_length=50)),
                ('subjects', models.TextField()),
                ('institute', models.CharField(max_length=200)),
                ('board', models.CharField(max_length=200)),
                ('level', models.CharField(default='N/A', max_length=50)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_qualifications', to='admissions.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='ExtraCurricularActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(blank=True, max_length=200)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('achievement', models.CharField(blank=True, max_length=200)),
                ('activity_year', models.PositiveIntegerField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_curricular_activities', to='admissions.applicant')),
            ],
        ),
    ]
