# Generated by Django 5.2 on 2025-06-22 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(help_text='Select the user account associated with this applicant.', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='academicqualification',
            name='applicant',
            field=models.ForeignKey(help_text='Select the applicant for this academic qualification.', on_delete=django.db.models.deletion.CASCADE, related_name='academic_qualifications', to='admissions.applicant'),
        ),
        migrations.AddField(
            model_name='extracurricularactivity',
            name='applicant',
            field=models.ForeignKey(help_text='Select the applicant for this activity record.', on_delete=django.db.models.deletion.CASCADE, related_name='extra_curricular_activities', to='admissions.applicant'),
        ),
    ]
