# Generated by Django 5.2 on 2025-05-23 17:34

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicsession',
            options={'ordering': ['-start_year'], 'verbose_name': 'Academic Session', 'verbose_name_plural': 'Academic Sessions'},
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='academicsession',
            name='start_date',
        ),
        migrations.AddField(
            model_name='academicsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicsession',
            name='description',
            field=models.TextField(blank=True, help_text='Optional: Add any additional information about this academic session'),
        ),
        migrations.AddField(
            model_name='academicsession',
            name='end_year',
            field=models.IntegerField(default=1, help_text='Enter the ending year of this academic session (e.g., 2025)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicsession',
            name='start_year',
            field=models.IntegerField(default=1, help_text='Enter the starting year of this academic session (e.g., 2021)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='academicsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Check this if this is the current academic session. Only one session can be active at a time.'),
        ),
        migrations.AlterField(
            model_name='academicsession',
            name='name',
            field=models.CharField(help_text="Enter the name of the academic session (e.g., '2021-2025', 'Fall 2021-Spring 2025')", max_length=50),
        ),
    ]
