# Generated by Django 5.2 on 2025-05-09 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicqualification',
            name='level',
        ),
        migrations.RemoveField(
            model_name='academicqualification',
            name='roll_no',
        ),
    ]
