# Generated by Django 5.2.3 on 2025-07-13 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_add_rejection_reason'),
        ('admissions', '0002_initial'),
    ]

    operations = [
    ]
