# Generated by Django 5.2 on 2025-07-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=1, help_text='Select the gender of the applicant.', max_length=6),
            preserve_default=False,
        ),
    ]
