# Generated by Django 5.2 on 2025-06-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], default=1, help_text='Select the preferred shift for the program.', max_length=10),
            preserve_default=False,
        ),
    ]
