# Generated by Django 5.2 on 2025-07-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_applicant_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection if application is rejected.', null=True),
        ),
    ]
