# Generated by Django 5.2 on 2025-05-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_remove_academicqualification_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicqualification',
            name='level',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
