"""
Django settings for campus360FYP project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*8m_21!ps4x3$^h72ccd%5js4i_^y+swwkx%qqk(y1^504m9*8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'users.CustomUser'

# Application definition

INSTALLED_APPS = [
    'django_daisy',
    'django.contrib.admin',
    'django.contrib.humanize',
    # 'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',            
    'users',           
    'widget_tweaks',
    'django_ckeditor_5',
    'site_elements' , 
    'announcements',
    'admissions',
    'academics',
    'faculty_staff',
    'courses',
    'students',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'campus360FYP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # template dir
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # 'django.template.context_processors.request',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.faculty_context',
                'core.context_processors.offices_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'campus360FYP.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# settings.py

# settings.py

# For development:
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"  # For collectstatic

# For media files (user-uploaded files):
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# settings.py
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'princeyahya052@gmail.com'
EMAIL_HOST_PASSWORD = 'pmyf uvlj sxfn gald'





# JET_DEFAULT_THEME = 'default'


# JET_THEMES = [
#     {'theme': 'default', 'color': '#47bac1', 'title': 'Default'},
#     {'theme': 'green', 'color': '#44b78b', 'title': 'Green'},
#     {'theme': 'light-green', 'color': '#2faa60', 'title': 'Light Green'},
#     {'theme': 'light-violet', 'color': '#a464c4', 'title': 'Light Violet'},
#     {'theme': 'light-blue', 'color': '#5EADDE', 'title': 'Light Blue'},
#     {'theme': 'light-gray', 'color': '#222', 'title': 'Light Gray'},
# ]



DAISY_SETTINGS = {
    'SITE_TITLE': '',  # The title of the site 
    'SITE_HEADER': 'Campus 360',  # Header text displayed in the admin panel
    'INDEX_TITLE': 'Hi, You are welcome ',  # The title for the index page of dashboard
    'SITE_LOGO': '/static/img/logo.png',  # Path to the logo image displayed in the sidebar
    'EXTRA_STYLES': [],  # List of extra stylesheets to be loaded in base.html (optional)
    'EXTRA_SCRIPTS': [
            'https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js',],  # List of extra script URLs to be loaded in base.html (optional)
    'LOAD_FULL_STYLES': False,
  # If True, loads full DaisyUI components in the admin (useful if you have custom template overrides)
    'SHOW_CHANGELIST_FILTER': True,  # If True, the filter sidebar will open by default on changelist views
    'DONT_SUPPORT_ME': True, # Hide github link in sidebar footer
    'SIDEBAR_FOOTNOTE': 'Developed by Muhammad Yahya ❤️', # add footnote to sidebar
     'APPS_REORDER': {
        # Custom order for your apps
        'auth': {
            'icon': 'fa-solid fa-person-military-pointing',  # FontAwesome icon for the 'auth' app
            'name': 'Assign roles',  # Custom name for the 'auth' app
            'hide': False,  # Whether to hide the 'auth' app from the sidebar
            'divider_title': "Permissions",  # Divider title for the 'auth' section
        },
        'users': {
            'icon': 'fa fa-user-cog',  # FontAwesome icon for the 'auth' app
            'name': 'Users',  # Custom name for the 'auth' app
            'hide': False,  # Whether to hide the 'auth' app from the sidebar
            'divider_title': "User Management",  # Divider title for the 'auth' section
        },
        'academics': {
            'icon': 'fa-solid fa-university',
            'name': 'Academics',
            'hide': False,
            'divider_title': "Academic Structure",
        },
        'admissions': {
            'icon': 'fa-solid fa-school',
            'name': 'Admissions',
            'hide': False,
            'divider_title': "Admissions Management",
        },
        'site_elements': {
            'icon': 'fa-solid fa-cogs',
            'name': 'Site Elements',
            'hide': False,
            'divider_title': "Site Content",
        },
        'announcements': {
            'icon': 'fa-solid fa-bullhorn',
            'name': 'Announcements',
            'hide': False,
            'divider_title': "Announcements",
        },
        'faculty_staff': {
            'icon': 'fa-solid fa-people-group',
            'name': 'Faculty & Staff',
            'hide': False,
            'divider_title': "People and Offices",
        },
        'courses': {
            'icon': 'fa-solid fa-book-open',
            'name': 'Courses',
            'hide': False,
            'divider_title': "Course Management",
        },
        'students': {
            'icon': 'fa-solid fa-user-graduate',
            'name': 'Students',
            'hide': False,
            'divider_title': "Student Management",
        },
        'core': {
            'icon': 'fa-solid fa-wrench',
            'name': 'Core Settings',
            'hide': False,
            'divider_title': "Site Configuration",
        },
    },
}



# CKEditor 5 Configuration (with upload support)
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'link',
            'bulletedList', 'numberedList', 'blockQuote', 'imageUpload'
        ],
    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|', 'bulletedList', 'numberedList',
            '|', 'blockQuote', 'imageUpload'
        ],
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
            'code', 'subscript', 'superscript', 'highlight', '|', 'codeBlock',
            'bulletedList', 'numberedList', 'todoList', '|', 'blockQuote', 'imageUpload',
            '|', 'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', '|',
            'alignment', '|', 'undo', 'redo'
        ],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side', '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]
        },
    }
}



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}