"""
Django settings for campus360FYP project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*8m_21!ps4x3$^h72ccd%5js4i_^y+swwkx%qqk(y1^504m9*8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['60f2-2404-3100-1ca5-5ce6-b564-87b9-ff3-6e7f.ngrok-free.app', 'localhost', '127.0.0.1']
CSRF_TRUSTED_ORIGINS = ['https://60f2-2404-3100-1ca5-5ce6-b564-87b9-ff3-6e7f.ngrok-free.app']

STRIPE_PUBLIC_KEY = 'pk_test_51RVc14DCFgsH63aPMLiGzlXEuqSGbyxbqTXyWsnqFbx6IXnTjDF0crV3RB3Avil0rAeRU7KVQsrA369EZdzQWmUx00numghDOP'
STRIPE_SECRET_KEY = 'sk_test_51RVc14DCFgsH63aPcCG3IteORSTlv0oPziVNNsLZkB3cx9Wtb9q7InvToT8CRHZf5wJ1pqsJGGdGe9LjOuzVAZ1P00STSNm7U3'
STRIPE_ENDPOINT_SECRET = 'whsec_etRtmwacOWudfKX2BIHNHgBgn6jb4djo'
SITE_URL = 'https://60f2-2404-3100-1ca5-5ce6-b564-87b9-ff3-6e7f.ngrok-free.app'
PAYMENT_SUCCESS_URL = f'{SITE_URL}/payments/success/?session_id={{CHECKOUT_SESSION_ID}}'
PAYMENT_CANCEL_URL = f'{SITE_URL}/payments/cancel/?session_id={{CHECKOUT_SESSION_ID}}'



AUTH_USER_MODEL = 'users.CustomUser'

# Application definition

INSTALLED_APPS = [
    'django_daisy',
    'django.contrib.admin',
    'django.contrib.humanize',
    # 'django.contrib.admin',  
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',            
    'users',           
    'widget_tweaks',
    'django_ckeditor_5',
    'site_elements' , 
    'announcements',
    'admissions',
    'academics',
    'faculty_staff',
    'courses',
    'students',
    'django_extensions',
    'learning_cycle',
    'payment',
    'background_task', #ya wesy pakadge k liy add kia gaya hai
    'bgtask'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'campus360FYP.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                # 'django.template.context_processors.request',
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.faculty_context',
                'core.context_processors.offices_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'campus360FYP.wsgi.application'


# Database 
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'college_db',
#         'USER': 'postgres',
#         'PASSWORD': '0000pppp',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }





# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Karachi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# settings.py

# settings.py

# For development:
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"  # For collectstatic

# For media files (user-uploaded files):
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# settings.py
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'princeyahya052@gmail.com'
EMAIL_HOST_PASSWORD = 'pmyf uvlj sxfn gald'









DAISY_SETTINGS = {
    'SITE_TITLE': '',  # The title of the site 
    'SITE_HEADER': 'Campus 360',  # Header text displayed in the admin panel
    'INDEX_TITLE': 'Hi, You are welcome ',  # The title for the index page of dashboard
    'SITE_LOGO': '/static/img/logo.png',  # Path to the logo image displayed in the sidebar
    'EXTRA_STYLES': [],  # List of extra stylesheets to be loaded in base.html (optional)
    'EXTRA_SCRIPTS': [
            'https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js',],  # List of extra script URLs to be loaded in base.html (optional)
    'LOAD_FULL_STYLES': False,
    'SHOW_CHANGELIST_FILTER': True,  # If True, the filter sidebar will open by default on changelist views
    'DONT_SUPPORT_ME': True, # Hide github link in sidebar footer
    'SIDEBAR_FOOTNOTE': 'Developed by Muhammad Yahya ❤️', # add footnote to sidebar
    'APPS_REORDER': {
        # Core and User Management first
'core': {
    'icon': 'fa-solid fa-wrench',
    'name': 'Core Settings',
    'hide': False,
    'divider_title': "Site Configuration",
    'priority': 10,
},
'users': {
    'icon': 'fa fa-user-cog',
    'name': 'Users',
    'hide': False,
    'divider_title': "User Management",
    'priority': 9,
},
'auth': {
    'icon': 'fa-solid fa-person-military-pointing',
    'name': 'Assign roles',
    'hide': False,
    'divider_title': "Permissions",
    'priority': 8,
},
'academics': {
    'icon': 'fa-solid fa-university',
    'name': 'Academics',
    'hide': False,
    'divider_title': "Academic Structure",
    'priority': 7,
},
'students': {
    'icon': 'fa-solid fa-user-graduate',
    'name': 'Students',
    'hide': False,
    'divider_title': "Student Management",
    'priority': 5,
},
'courses': {
    'icon': 'fa-solid fa-book-open',
    'name': 'Courses',
    'hide': False,
    'divider_title': "Course and Semester",
    'priority': 4,
},
'faculty_staff': {
    'icon': 'fa-solid fa-people-group',
    'name': 'Faculty and Staff',
    'hide': False,
    'divider_title': "People and Offices",
    'priority': 6,
},
'admissions': {
    'icon': 'fa-solid fa-school',
    'name': 'Admissions',
    'hide': False,
    'divider_title': "Admissions Management",
    'priority': 8,
},
'announcements': {
    'icon': 'fa-solid fa-bullhorn',
    'name': 'Announcements',
    'hide': False,
    'divider_title': "Announcements",
    'priority': 2,
},
'site_elements': {
    'icon': 'fa-solid fa-cogs',
    'name': 'Site Elements',
    'hide': False,
    'divider_title': "Site Content",
    'priority': 3,
},
    }
}



# CKEditor 5 Configuration (with upload support)
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'link',
            'bulletedList', 'numberedList', 'blockQuote', 'imageUpload'
        ],
    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|', 'bulletedList', 'numberedList',
            '|', 'blockQuote', 'imageUpload'
        ],
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
            'code', 'subscript', 'superscript', 'highlight', '|', 'codeBlock',
            'bulletedList', 'numberedList', 'todoList', '|', 'blockQuote', 'imageUpload',
            '|', 'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', '|',
            'alignment', '|', 'undo', 'redo'
        ],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side', '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]
        },
    }
}



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        '': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}