# Generated by Django 5.2 on 2025-07-10 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('faculty_staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='officestaff',
            name='user',
            field=models.OneToOneField(help_text='Select the user account associated with this staff member.', on_delete=django.db.models.deletion.CASCADE, related_name='officestaff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.ForeignKey(help_text='Select the department this teacher belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='academics.department'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(help_text='Select the user account associated with this teacher.', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacherdetails',
            name='teacher',
            field=models.OneToOneField(help_text='Select the teacher to associate these details with.', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='faculty_staff.teacher'),
        ),
    ]
