# Generated by Django 5.2 on 2025-07-16 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('admissions', '0002_initial'),
        ('faculty_staff', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Enter the required amount for this fund', max_digits=10)),
                ('description', models.TextField(help_text='Enter a description of what this fund is for')),
                ('due_date', models.DateField(help_text='Set the deadline for this fund')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this fund was created')),
                ('is_active', models.BooleanField(default=True, help_text='Check this if the fund is currently active')),
                ('academic_sessions', models.ManyToManyField(help_text='Select the academic sessions this fund applies to', related_name='department_funds', to='admissions.academicsession')),
                ('department', models.ForeignKey(help_text='Select the department this fund belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='department_funds', to='academics.department')),
                ('hod', models.ForeignKey(help_text='Select the HOD who created this fund', limit_choices_to={'designation': 'head_of_department'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_funds', to='faculty_staff.teacher')),
                ('programs', models.ManyToManyField(help_text='Select the programs this fund applies to', related_name='department_funds', to='academics.program')),
                ('semesters', models.ManyToManyField(help_text='Select the semesters this fund applies to', related_name='department_funds', to='academics.semester')),
            ],
            options={
                'verbose_name': 'Department Fund',
                'verbose_name_plural': 'Department Funds',
                'ordering': ['-created_at'],
            },
        ),
    ]
