# Generated by Django 5.2 on 2025-06-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_staff', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(blank=True, choices=[('visitor', 'Visitor'), ('contract', 'Contract Based'), ('permanent', 'Permanent')], help_text='Select the employment type of the teacher (optional).', max_length=20, null=True)),
                ('salary_per_lecture', models.DecimalField(blank=True, decimal_places=2, help_text="Enter the teacher's salary per lecture (optional).", max_digits=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('on_break', 'On Break'), ('on_lecture', 'On Lecture'), ('on_leave', 'On Leave'), ('available', 'Available')], help_text='Select the current status of the teacher (optional).', max_length=20, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Automatically updated with the last modification date.')),
                ('teacher', models.OneToOneField(help_text='Select the teacher to associate these details with.', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='faculty_staff.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Details',
                'verbose_name_plural': 'Teacher Details',
            },
        ),
    ]
