# Generated by Django 5.2 on 2025-05-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_staff', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='designation',
            field=models.CharField(choices=[('head_of_department', 'Head of Department'), ('professor', 'Professor')], help_text='Select the official designation or role of the teacher within the department.', max_length=100),
        ),
    ]
