# Generated by Django 5.2 on 2025-06-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_staff', '0003_teacherdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdetails',
            name='fixed_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Enter the teacher's fix salary (optional).", max_digits=10, null=True),
        ),
    ]
