# Generated by Django 5.2 on 2025-07-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_staff', '0003_departmentfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentfund',
            name='fundtype',
            field=models.CharField(default=1, help_text='type of fund', max_length=100),
            preserve_default=False,
        ),
    ]
