# Generated by Django 5.2 on 2025-07-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_staff', '0004_departmentfund_fundtype'),
        ('students', '0003_studentfundpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentfund',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Students associated with this fund and their payment status', related_name='department_funds', through='students.StudentFundPayment', to='students.student'),
        ),
    ]
