# Generated by Django 5.2 on 2025-07-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_staff', '0005_departmentfund_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='officestaff',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=1, help_text='Select the gender of the office staff member.', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default=1, help_text='Select the gender of the teacher.', max_length=6),
            preserve_default=False,
        ),
    ]
