# Generated by Django 5.2 on 2025-07-16 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_staff', '0006_officestaff_gender_teacher_gender'),
        ('students', '0004_studentfundpayment_verified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentfund',
            name='students',
            field=models.ManyToManyField(blank=True, help_text='Students associated with this fund and their payment status', related_name='department_funds', through='students.StudentFundPayment', through_fields=('fund', 'student'), to='students.student'),
        ),
    ]
