# Generated by Django 5.2 on 2025-07-27 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('admissions', '0004_applicant_rejection_reason'),
        ('courses', '0009_examresult_is_fail'),
        ('faculty_staff', '0007_alter_departmentfund_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamDateSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('midterm', 'Midterm'), ('final', 'Final'), ('practical', 'Practical'), ('other', 'Other')], help_text='Select the type of exam.', max_length=20)),
                ('exam_date', models.DateField(help_text='Select the date of the exam.')),
                ('start_time', models.TimeField(help_text='Select the start time of the exam.')),
                ('end_time', models.TimeField(help_text='Select the end time of the exam.')),
                ('exam_center', models.CharField(help_text='Enter the exam center or location (e.g., Room 101, Building A).', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this exam schedule was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this exam schedule was last updated.')),
                ('academic_session', models.ForeignKey(help_text='Select the academic session for this exam.', on_delete=django.db.models.deletion.CASCADE, related_name='exam_datesheets', to='admissions.academicsession')),
                ('course_offering', models.ForeignKey(help_text='Select the course offering for this exam.', on_delete=django.db.models.deletion.CASCADE, related_name='exam_datesheets', to='courses.courseoffering')),
                ('program', models.ForeignKey(help_text='Select the program for this exam.', on_delete=django.db.models.deletion.CASCADE, related_name='exam_datesheets', to='academics.program')),
                ('semester', models.ForeignKey(help_text='Select the semester for this exam.', on_delete=django.db.models.deletion.CASCADE, related_name='exam_datesheets', to='academics.semester')),
            ],
            options={
                'verbose_name': 'Exam Datesheet',
                'verbose_name_plural': 'Exam Datesheets',
                'ordering': ['exam_date', 'start_time'],
                'unique_together': {('course_offering', 'exam_type', 'academic_session', 'semester')},
            },
        ),
    ]
