# Generated by Django 5.2 on 2025-05-21 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('faculty_staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Enter the unique course code (e.g., CS101).', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Enter the full name of the course (e.g., Introduction to Programming).', max_length=200)),
                ('credits', models.PositiveIntegerField(help_text='Enter the number of credit hours for this course.')),
                ('is_active', models.BooleanField(default=True, help_text='Check this if the course is currently active and can be offered.')),
                ('description', models.TextField(blank=True, help_text='Provide a brief description or syllabus summary for the course.')),
                ('prerequisites', models.ManyToManyField(blank=True, help_text='Select any courses that are required to be completed before taking this course (optional).', related_name='required_for', to='courses.course')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering_type', models.CharField(choices=[('core', 'Core / Compulsory'), ('major', 'Major'), ('minor', 'Minor'), ('elective', 'Elective'), ('foundation', 'Foundation'), ('gen_ed', 'General Education'), ('lab', 'Lab / Practical'), ('seminar', 'Seminar'), ('capstone', 'Capstone / Final Project'), ('internship', 'Internship / Training'), ('service', 'Service Course'), ('remedial', 'Remedial / Non-Credit')], default='core', help_text='Specify how this course offering fits into a program (e.g., Major, Elective, Foundation, etc.).', max_length=30)),
                ('course', models.ForeignKey(help_text='Select the core course being offered.', on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='courses.course')),
                ('department', models.ForeignKey(blank=True, help_text='Select the department offering this course (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='academics.department')),
                ('program', models.ForeignKey(blank=True, help_text='Select the program this course offering belongs to (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='academics.program')),
                ('teacher', models.ForeignKey(help_text='Select the teacher assigned to teach this course offering.', on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='faculty_staff.teacher')),
            ],
            options={
                'verbose_name': 'Course Offering',
                'verbose_name_plural': 'Course Offerings',
                'unique_together': {('course', 'teacher', 'program', 'department', 'offering_type')},
            },
        ),
    ]
