# Generated by Django 5.2 on 2025-06-01 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('faculty_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='created_by',
            field=models.ForeignKey(help_text='The teacher who created this assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to='faculty_staff.teacher'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(help_text='The assignment this submission is for.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(help_text='The teacher who graded this submission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to='faculty_staff.teacher'),
        ),
    ]
