# Generated by Django 5.2 on 2025-05-25 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('courses', '0001_initial'),
        ('faculty_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='teacher',
            field=models.ForeignKey(help_text='Select the teacher assigned to teach this course offering.', on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='faculty_staff.teacher'),
        ),
        migrations.AddField(
            model_name='semester',
            name='program',
            field=models.ForeignKey(help_text='Select the program this semester belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.program'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='semester',
            field=models.ForeignKey(help_text='Select the semester for this offering.', on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='courses.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('program', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='courseoffering',
            unique_together={('course', 'teacher', 'program', 'department', 'academic_session', 'semester', 'offering_type')},
        ),
    ]
