# Generated by Django 5.2 on 2025-05-23 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('admissions', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='academic_session',
            field=models.ForeignKey(default=1, help_text='Select the academic session for this offering.', on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='admissions.academicsession'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='offering_type',
            field=models.CharField(choices=[('core', 'Core / Compulsory'), ('major', 'Major'), ('minor', 'Minor'), ('elective', 'Elective'), ('foundation', 'Foundation'), ('gen_ed', 'General Education'), ('lab', 'Lab / Practical'), ('seminar', 'Seminar'), ('capstone', 'Capstone / Final Project'), ('internship', 'Internship / Training'), ('service', 'Service Course'), ('remedial', 'Remedial / Non-Credit')], default='core', help_text='Specify how this course offering fits into a program.', max_length=30),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(help_text='Semester number in the program sequence')),
                ('name', models.CharField(help_text="Name of the semester (e.g., 'Foundation', 'Advanced')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of what this semester covers')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this semester is currently active')),
                ('learning_level', models.CharField(choices=[('foundation', 'Foundation Level'), ('basic', 'Basic Level'), ('intermediate', 'Intermediate Level'), ('advanced', 'Advanced Level'), ('specialized', 'Specialized Level'), ('professional', 'Professional Level'), ('capstone', 'Capstone Level')], help_text='The learning level of this semester', max_length=20)),
                ('program', models.ForeignKey(help_text='Select the program this semester belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.program')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'ordering': ['program', 'number'],
                'unique_together': {('program', 'number')},
            },
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='semester',
            field=models.ForeignKey(help_text='Select the semester for this offering.', on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='courses.semester'),
        ),
    ]
