# Generated by Django 5.2 on 2025-05-15 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_program_degree_type_alter_department_options_and_more'),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='session',
        ),
        migrations.AddField(
            model_name='semester',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.program'),
            preserve_default=False,
        ),
    ]
