# Generated by Django 5.2 on 2025-05-25 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_studentgrade_grade_and_more'),
        ('courses', '0002_initial'),
        ('students', '0003_alter_student_current_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseoffering',
            name='semester',
            field=models.ForeignKey(help_text='Select the semester for this offering.', on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='academics.semester'),
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
