# Generated by Django 5.2 on 2025-06-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('admissions', '0001_initial'),
        ('courses', '0002_initial'),
        ('faculty_staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='student',
            field=models.ForeignKey(help_text='The student who submitted this assignment.', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='students.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to='faculty_staff.teacher'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Select any courses that are required to be completed before taking this course (optional).', related_name='required_for', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='academic_session',
            field=models.ForeignKey(help_text='Select the academic session for this offering.', on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='admissions.academicsession'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='course',
            field=models.ForeignKey(help_text='Select the core course being offered.', on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Select the department offering this course (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='academics.department'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='program',
            field=models.ForeignKey(blank=True, help_text='Select the program this course offering belongs to (optional).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='academics.program'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='semester',
            field=models.ForeignKey(help_text='Select the semester for this offering.', on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='teacher',
            field=models.ForeignKey(help_text='Select the teacher assigned to teach this course offering.', on_delete=django.db.models.deletion.CASCADE, related_name='course_offerings', to='faculty_staff.teacher'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.courseoffering'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.courseoffering'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='course_offering',
            field=models.ForeignKey(help_text='The course offering this exam result is for.', on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='courses.courseoffering'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='graded_by',
            field=models.ForeignKey(help_text='The teacher who graded this exam.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_results', to='faculty_staff.teacher'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='student',
            field=models.ForeignKey(help_text='The student this result pertains to.', on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='students.student'),
        ),
        migrations.AddField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(help_text='The teacher who created this notice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to='faculty_staff.teacher'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='courses.courseoffering'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_materials', to='faculty_staff.teacher'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='courses.courseoffering'),
        ),
        migrations.AddField(
            model_name='venue',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.department'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.venue'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'course_offering', 'date', 'shift')},
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('course_offering', 'student', 'exam_type')},
        ),
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together={('course_offering', 'day', 'start_time', 'venue')},
        ),
    ]
