# Generated by Django 5.2 on 2025-06-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('both', 'Both')], default='morning', help_text='Select the shift for this course offering.', max_length=10),
        ),
    ]
