# Generated by Django 5.2 on 2025-07-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examresult',
            name='practical_obtained',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='practical_total',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='project_obtained',
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='project_total',
        ),
        migrations.AddField(
            model_name='examresult',
            name='percentage',
            field=models.FloatField(blank=True, help_text='Overall percentage for the exam result.', null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='final_total',
            field=models.PositiveIntegerField(help_text='Total marks for Final Exam (credit_hours * 14).'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='midterm_total',
            field=models.PositiveIntegerField(help_text='Total marks for Midterm Exam (credit_hours * 4).'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='sessional_total',
            field=models.PositiveIntegerField(help_text='Total marks for Sessional (credit_hours * 2).'),
        ),
    ]
