# Generated by Django 5.2 on 2025-06-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='remarks',
            field=models.TextField(blank=True, help_text="Additional remarks or comments on the student's performance.", null=True),
        ),
    ]
