# Generated by Django 5.2 on 2025-05-26 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseoffering_unique_together_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoffering',
            name='current_enrollment',
        ),
        migrations.RemoveField(
            model_name='courseoffering',
            name='max_capacity',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='course_offering',
        ),
    ]
