# Generated by Django 5.2 on 2025-07-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_examresult_practical_obtained_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='practical_obtained',
            field=models.PositiveIntegerField(blank=True, help_text='Marks obtained in Sessional.', null=True),
        ),
        migrations.AddField(
            model_name='examresult',
            name='practical_total',
            field=models.PositiveIntegerField(default=1, help_text='Total marks for practical (credit_hours * 20).'),
            preserve_default=False,
        ),
    ]
