# Generated by Django 5.2 on 2025-06-18 04:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseoffering_shift'),
        ('faculty_staff', '0002_initial'),
        ('students', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('leave', 'Leave')], default='present', max_length=10)),
                ('shift', models.CharField(blank=True, choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=10, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.courseoffering')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to='faculty_staff.teacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student')),
            ],
            options={
                'ordering': ['date', 'student'],
                'unique_together': {('student', 'course_offering', 'date', 'shift')},
            },
        ),
    ]
