# Generated by Django 5.2 on 2025-07-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_examresult_practical_obtained_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='total_marks',
            field=models.FloatField(default=1, help_text='Overall marks for the exam result.'),
            preserve_default=False,
        ),
    ]
