# Generated by Django 5.2 on 2025-06-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_question_alter_venue_name_option_quiz_question_quiz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='content',
            field=models.TextField(blank=True, help_text='Rich text content of the submission.'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(blank=True, help_text='The file submitted by the student.', null=True, upload_to='submissions/'),
        ),
    ]
