# Generated by Django 5.2 on 2025-05-26 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_courseoffering_current_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='current_enrollment',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
