# Generated by Django 5.2 on 2025-06-19 02:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_attendance'),
        ('faculty_staff', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studymaterial',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='file',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='study_materials/'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='study_materials', to='faculty_staff.teacher'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='topic',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='useful_links',
            field=models.TextField(blank=True, help_text='Enter URLs separated by newlines'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_materials', to='courses.courseoffering'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
