# Generated by Django 5.2 on 2025-07-13 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_examresult_total_marks'),
        ('faculty_staff', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='practical_obtained',
            field=models.PositiveIntegerField(blank=True, help_text='Marks obtained in Practical.', null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='total_marks',
            field=models.FloatField(default=0.0, help_text='Overall marks obtained for the exam result.'),
        ),
        migrations.CreateModel(
            name='LectureReplacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replacement_type', models.CharField(choices=[('temporary', 'Temporary'), ('permanent', 'Permanent')], default='temporary', help_text='Specify if the replacement is temporary (one day) or permanent.', max_length=10)),
                ('replacement_date', models.DateField(blank=True, help_text='For temporary replacements, specify the date of the replacement. Leave blank for permanent replacements.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the replacement was created.')),
                ('course_offering', models.ForeignKey(help_text='Select the course offering for which the teacher is being replaced.', on_delete=django.db.models.deletion.CASCADE, related_name='replacements', to='courses.courseoffering')),
                ('original_teacher', models.ForeignKey(help_text='Select the original teacher being replaced.', on_delete=django.db.models.deletion.CASCADE, related_name='replaced_lectures', to='faculty_staff.teacher')),
                ('replacement_teacher', models.ForeignKey(help_text='Select the teacher who will replace the original teacher.', on_delete=django.db.models.deletion.CASCADE, related_name='replacement_lectures', to='faculty_staff.teacher')),
            ],
            options={
                'verbose_name': 'Lecture Replacement',
                'verbose_name_plural': 'Lecture Replacements',
                'unique_together': {('course_offering', 'original_teacher', 'replacement_date')},
            },
        ),
    ]
