# Generated by Django 5.2 on 2025-07-01 15:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('courses', '0006_assignmentsubmission_content_and_more'),
        ('faculty_staff', '0004_teacherdetails_fixed_salary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'assignments'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-is_pinned', '-created_at']},
        ),
        migrations.AddField(
            model_name='notice',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notices/attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='notice',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='notices', to='academics.department'),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notice',
            name='notice_type',
            field=models.CharField(choices=[('general', 'General'), ('academic', 'Academic'), ('event', 'Event'), ('exam', 'Exam'), ('holiday', 'Holiday'), ('other', 'Other')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notice',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notices', to='faculty_staff.teacher'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['-created_at'], name='courses_not_created_9204e3_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['notice_type'], name='courses_not_notice__21da9d_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['priority'], name='courses_not_priorit_8ffd57_idx'),
        ),
        migrations.AddIndex(
            model_name='notice',
            index=models.Index(fields=['is_active'], name='courses_not_is_acti_745d98_idx'),
        ),
    ]
