# Generated by Django 5.2 on 2025-06-20 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_studymaterial_options_and_more'),
        ('faculty_staff', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name_plural': 'assignments'},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='file',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='assignment',
            name='max_points',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='resource_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='assignments/resources/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='faculty_staff.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.courseoffering'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
