# Generated by Django 5.2 on 2025-07-14 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_examresult_practical_obtained_and_more'),
        ('faculty_staff', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoffering',
            name='replacement_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_course_offerings', to='faculty_staff.teacher'),
        ),
    ]
