# Generated by Django 5.2 on 2025-07-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('admissions', '0002_initial'),
        ('courses', '0007_alter_assignment_options_alter_notice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='departments',
        ),
        migrations.AddField(
            model_name='notice',
            name='programs',
            field=models.ManyToManyField(blank=True, help_text='Select programs this notice applies to (leave blank for all programs).', related_name='notices', to='academics.program'),
        ),
        migrations.AddField(
            model_name='notice',
            name='sessions',
            field=models.ManyToManyField(blank=True, help_text='Select academic sessions this notice applies to (leave blank for all sessions).', related_name='notices', to='admissions.academicsession'),
        ),
    ]
