# Generated by Django 5.2 on 2025-06-20 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_venue_timetableslot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetableslot',
            unique_together={('course_offering', 'day', 'start_time', 'venue')},
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.venue'),
        ),
        migrations.RemoveField(
            model_name='timetableslot',
            name='created_at',
        ),
    ]
