# Generated by Django 5.2 on 2025-07-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_courseoffering_replacement_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='is_fail',
            field=models.BooleanField(default=False, help_text='Indicates if the student failed this course.'),
        ),
    ]
