# Generated by Django 5.2 on 2025-06-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_timetableslot_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lab_work',
            field=models.IntegerField(default=0, help_text='Enter the number of lab hours per week for this course (if applicable).'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10),
        ),
    ]
