# Generated by Django 5.2 on 2025-07-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_examresult_is_fail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturereplacement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the replacement is still active.'),
        ),
    ]
