# Generated by Django 5.2 on 2025-07-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lecturereplacement_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Whether the result is published to students'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When the result was published to students', null=True),
        ),
    ]
