# Generated by Django 5.2.4 on 2025-08-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_examresult_is_published_examresult_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='code_language',
            field=models.CharField(choices=[('none', 'None'), ('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('c', 'C'), ('cpp', 'C++'), ('java', 'Java'), ('php', 'PHP'), ('sql', 'SQL')], default='none', help_text='Programming language for code submissions.', max_length=20),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='formatted_content',
            field=models.TextField(blank=True, help_text='Formatted content for display purposes.'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submission_type',
            field=models.CharField(choices=[('text', 'Rich Text'), ('code', 'Code')], default='text', help_text='Type of submission content.', max_length=10),
        ),
    ]
