# Generated by Django 5.2.4 on 2025-08-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_assignmentsubmission_code_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentsubmission',
            old_name='content',
            new_name='text_content',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='code_content',
            field=models.TextField(blank=True, help_text='Code content of the submission.'),
        ),
    ]
