# Generated by Django 5.2 on 2025-06-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the alumnus/alumna.', max_length=100)),
                ('graduation_year', models.PositiveIntegerField(help_text='Enter the year the alumnus/alumna graduated.')),
                ('profession', models.CharField(help_text='Enter the current profession or occupation of the alumnus/alumna.', max_length=200)),
                ('testimonial', models.TextField(help_text='Enter the testimonial or quote from the alumnus/alumna.')),
                ('image', models.ImageField(blank=True, help_text='Upload a picture of the alumnus/alumna (optional).', null=True, upload_to='alumni/')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title for the gallery image.', max_length=200)),
                ('image', models.ImageField(help_text='Upload the image for the gallery.', upload_to='gallery/')),
                ('date_added', models.DateTimeField(auto_now_add=True, help_text='The date and time the image was added to the gallery.')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter a title for the slider image.', max_length=200)),
                ('image', models.ImageField(help_text='Upload the image for the slider.', upload_to='slider/')),
                ('is_active', models.BooleanField(default=True, help_text='Check to make this slider image active on the website.')),
            ],
        ),
    ]
