# Generated by Django 5.2.5 on 2025-08-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_elements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery', 'verbose_name_plural': 'Gallery'},
        ),
    ]
