# Generated by Django 5.2 on 2025-05-25 05:46

import autoslug.fields
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the event.', max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='A unique, web-friendly identifier for the event. Automatically generated from the title.', populate_from='title', unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Provide a detailed description of the event.', verbose_name='Text')),
                ('event_start_date', models.DateTimeField(help_text='Select the date and time when the event starts (YYYY-MM-DD HH:MM).')),
                ('event_end_date', models.DateTimeField(help_text='Select the date and time when the event ends (YYYY-MM-DD HH:MM).')),
                ('location', models.CharField(help_text='Enter the location where the event will take place.', max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Upload an image related to the event (optional).', null=True, upload_to='events/')),
                ('created_at', models.DateField(help_text='The date when this event record was created.')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the news article.', max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, help_text='A unique, web-friendly identifier for the news article. Automatically generated from the title.', populate_from='title', unique=True)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Enter the main content of the news article.', verbose_name='Text')),
                ('published_date', models.DateTimeField(auto_now_add=True, help_text='The date and time the news article was published.')),
                ('is_published', models.BooleanField(default=True, help_text='Check this to make the news article visible on the website.')),
            ],
        ),
    ]
