# Generated by Django 5.2 on 2025-07-09 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('admissions', '0002_initial'),
        ('faculty_staff', '0004_teacherdetails_fixed_salary'),
        ('students', '0004_student_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('computer_fee', models.BooleanField(default=False)),
                ('computer_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('examination_fund', models.BooleanField(default=False)),
                ('examination_fund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tuition_fee', models.BooleanField(default=False)),
                ('tuition_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('others', models.BooleanField(default=False)),
                ('others_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('evening_fund', models.BooleanField(default=False)),
                ('evening_fund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_fees', to='fee_management.feetype')),
            ],
        ),
        migrations.CreateModel(
            name='FeeToProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], help_text='Select the preferred shift for the students.', max_length=10)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.academicsession')),
                ('programs', models.ManyToManyField(to='academics.program')),
                ('semester_number', models.ManyToManyField(to='academics.semester')),
                ('SemesterFee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_fees', to='fee_management.semesterfee')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('receipt_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('semester_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fee_management.semesterfee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='FeeVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('due_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty_staff.office')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='students.student')),
                ('semester_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='fee_management.semesterfee')),
            ],
            options={
                'unique_together': {('student', 'semester', 'semester_fee')},
            },
        ),
    ]
