# Generated by Django 5.2 on 2025-07-08 08:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('admissions', '0002_initial'),
        ('students', '0004_student_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('computer_fee', models.BooleanField(default=False)),
                ('examination_fund', models.BooleanField(default=False)),
                ('tuition_fee', models.BooleanField(default=False)),
                ('others', models.BooleanField(default=False)),
                ('evening_fund', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_fees', to='fee_management.feetype')),
            ],
        ),
        migrations.CreateModel(
            name='FeeToProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_number', models.IntegerField()),
                ('academic_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_fees', to='admissions.academicsession')),
                ('programs', models.ManyToManyField(related_name='semester_fees', to='academics.program')),
                ('SemesterFee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_fees', to='fee_management.semesterfee')),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('receipt_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('remarks', models.TextField(blank=True)),
                ('semester_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fee_management.semesterfee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='students.student')),
            ],
        ),
    ]
