# Generated by Django 5.2 on 2025-07-10 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('admissions', '0001_initial'),
        ('faculty_staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('computer_fee', models.BooleanField(default=False)),
                ('computer_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('examination_fund', models.BooleanField(default=False)),
                ('examination_fund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tuition_fee', models.BooleanField(default=False)),
                ('tuition_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('others', models.BooleanField(default=False)),
                ('others_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('evening_fund', models.BooleanField(default=False)),
                ('evening_fund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], help_text='Select the preferred shift for the students.', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentFeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('receipt_number', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeToProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.academicsession')),
                ('programs', models.ManyToManyField(to='academics.program')),
                ('semester_number', models.ManyToManyField(to='academics.semester')),
            ],
        ),
        migrations.CreateModel(
            name='FeeVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('due_date', models.DateField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='faculty_staff.office')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_vouchers', to='academics.semester')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
