# Generated by Django 5.2 on 2025-07-10 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fee_management', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feevoucher',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='students.student'),
        ),
        migrations.AddField(
            model_name='semesterfee',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_fees', to='fee_management.feetype'),
        ),
        migrations.AddField(
            model_name='feevoucher',
            name='semester_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='fee_management.semesterfee'),
        ),
        migrations.AddField(
            model_name='feetoprogram',
            name='SemesterFee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_fees', to='fee_management.semesterfee'),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='semester_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fee_management.semesterfee'),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='students.student'),
        ),
        migrations.AddField(
            model_name='feevoucher',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher', to='fee_management.studentfeepayment'),
        ),
        migrations.AlterUniqueTogether(
            name='feevoucher',
            unique_together={('student', 'semester', 'semester_fee')},
        ),
    ]
