# Generated by Django 5.2 on 2025-07-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0002_feetoprogram_semesterfee_feevoucher_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semesterfee',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='semesterfee',
            name='computer_fee',
        ),
        migrations.RemoveField(
            model_name='semesterfee',
            name='computer_fee_amount',
        ),
        migrations.RemoveField(
            model_name='semesterfee',
            name='evening_fund',
        ),
        migrations.RemoveField(
            model_name='semesterfee',
            name='evening_fund_amount',
        ),
        migrations.RemoveField(
            model_name='semesterfee',
            name='examination_fund',
        ),
        migrations.RemoveField(
            model_name='semesterfee',
            name='examination_fund_amount',
        ),
        migrations.RemoveField(
            model_name='semesterfee',
            name='others',
        ),
        migrations.RemoveField(
            model_name='semesterfee',
            name='others_amount',
        ),
        migrations.RemoveField(
            model_name='semesterfee',
            name='tuition_fee',
        ),
        migrations.RemoveField(
            model_name='semesterfee',
            name='tuition_fee_amount',
        ),
        migrations.AddField(
            model_name='semesterfee',
            name='dynamic_fees',
            field=models.JSONField(default=dict),
        ),
    ]
