# Generated by Django 5.2 on 2025-07-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('fee_management', '0002_semesterfee_computer_fee_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feetoprogram',
            name='semester_number',
        ),
        migrations.AddField(
            model_name='feetoprogram',
            name='semester_number',
            field=models.ManyToManyField(related_name='semester_fees', to='academics.semester'),
        ),
    ]
