# Generated by Django 5.2 on 2025-07-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0002_add_shift_to_semesterfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feetoprogram',
            name='shift',
        ),
        migrations.AlterField(
            model_name='semesterfee',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], help_text='Select the preferred shift for the students.', max_length=10),
        ),
    ]
