# Generated by Django 5.2 on 2025-07-19 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('admissions', '0003_applicant_gender'),
        ('fee_management', '0003_remove_semesterfee_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeritList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_number', models.PositiveIntegerField(help_text='Sequence number of this merit list')),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], default='Morning', help_text='Shift for the merit list', max_length=10)),
                ('generation_date', models.DateField(auto_now_add=True)),
                ('total_seats', models.PositiveIntegerField(default=0, help_text='Total number of applicants in this merit list')),
                ('seccured_seats', models.PositiveIntegerField(default=0, help_text='Number of seats secured from this merit list')),
                ('valid_until', models.DateTimeField(help_text='Date until which this merit list is valid')),
                ('is_active', models.BooleanField(default=True, help_text='Is this the currently active merit list?')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this merit list')),
                ('academic_session', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merit_lists', to='admissions.academicsession')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_lists', to='academics.program')),
            ],
            options={
                'ordering': ['-generation_date'],
                'unique_together': {('program', 'list_number', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='MeritListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merit_position', models.PositiveIntegerField(help_text='Ranking position in the merit list')),
                ('relevant_percentage', models.DecimalField(decimal_places=2, help_text="Relevant percentage based on program level (Intermediate for BS, Bachelor's for MS)", max_digits=5)),
                ('passing_year', models.PositiveIntegerField(blank=True, help_text='Passing year of the qualification used', null=True)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Marks obtained in the qualification used', max_digits=7, null=True)),
                ('status', models.CharField(choices=[('selected', 'Selected'), ('admitted', 'Admitted')], default='selected', help_text='Current status of the candidate in this merit list', max_length=20)),
                ('selection_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, help_text='Any additional remarks about this candidate')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_list_entries', to='admissions.applicant')),
                ('merit_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fee_management.meritlist')),
                ('qualification_used', models.ForeignKey(blank=True, help_text='Reference to the academic qualification used for merit calculation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.academicqualification')),
            ],
            options={
                'ordering': ['merit_position'],
                'unique_together': {('merit_list', 'applicant')},
            },
        ),
    ]
