# Generated by Django 5.2 on 2025-07-10 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('faculty_staff', '0004_teacherdetails_fixed_salary'),
        ('fee_management', '0003_remove_feetoprogram_shift_alter_semesterfee_shift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feevoucher',
            options={'ordering': ['-generated_at']},
        ),
        migrations.AddField(
            model_name='feevoucher',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feevoucher',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feevoucher',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher', to='fee_management.studentfeepayment'),
        ),
        migrations.AlterField(
            model_name='feevoucher',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='faculty_staff.office'),
        ),
        migrations.AlterField(
            model_name='feevoucher',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_vouchers', to='academics.semester'),
        ),
    ]
