# Generated by Django 5.2 on 2025-07-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0004_alter_feevoucher_options_feevoucher_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeepayment',
            name='receipt_number',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
