# Generated by Django 5.2.4 on 2025-08-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('fee_management', '0005_officetohodnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='officetohodnotification',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='academics.department'),
        ),
    ]
