# Generated by Django 5.2.3 on 2025-07-13 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('admissions', '0002_initial'),
        ('fee_management', '0005_alter_studentfeepayment_receipt_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeritList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_number', models.PositiveIntegerField(help_text='Sequence number of this merit list')),
                ('generation_date', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField(help_text='Date until which this merit list is valid')),
                ('is_active', models.BooleanField(default=True, help_text='Is this the currently active merit list?')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes about this merit list')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_lists', to='academics.program')),
            ],
            options={
                'ordering': ['-generation_date'],
                'unique_together': {('program', 'list_number')},
            },
        ),
        migrations.CreateModel(
            name='MeritListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intermediate_marks', models.DecimalField(decimal_places=2, help_text='Percentage marks from intermediate/FSc', max_digits=5)),
                ('merit_position', models.PositiveIntegerField(help_text='Ranking position in the merit list')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_list_entries', to='admissions.applicant')),
                ('merit_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fee_management.meritlist')),
                ('qualification', models.ForeignKey(blank=True, help_text='Reference to the academic qualification used for merit calculation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.academicqualification')),
            ],
            options={
                'ordering': ['merit_position'],
                'unique_together': {('merit_list', 'applicant')},
            },
        ),
    ]
