# Generated by Django 5.2.3 on 2025-07-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0006_meritlist_meritlistentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='meritlist',
            name='seccured_seats',
            field=models.PositiveIntegerField(default=0, help_text='Number of seats secured in this merit list'),
        ),
        migrations.AddField(
            model_name='meritlist',
            name='total_applicants',
            field=models.PositiveIntegerField(default=0, help_text='Total number of applicants in this merit list'),
        ),
        migrations.DeleteModel(
            name='MeritListEntry',
        ),
    ]
