# Generated by Django 5.2.3 on 2025-07-13 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_merge_0002_add_rejection_reason_0002_initial'),
        ('fee_management', '0007_meritlist_seccured_seats_meritlist_total_applicants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeritListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merit_position', models.PositiveIntegerField(help_text='Ranking position in the merit list')),
                ('relevant_percentage', models.DecimalField(decimal_places=2, help_text="Relevant percentage based on program level (Intermediate for BS, Bachelor's for MS)", max_digits=5)),
                ('status', models.CharField(choices=[('selected', 'Selected'), ('pending', 'Pending')], default='selected', help_text='Current status of the candidate in this merit list', max_length=20)),
                ('selection_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, help_text='Any additional remarks about this candidate')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merit_list_entries', to='admissions.applicant')),
                ('merit_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='fee_management.meritlist')),
                ('qualification_used', models.ForeignKey(blank=True, help_text='Reference to the academic qualification used for merit calculation', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admissions.academicqualification')),
            ],
            options={
                'ordering': ['merit_position'],
                'unique_together': {('merit_list', 'applicant')},
            },
        ),
    ]
