# Generated by Django 5.2.3 on 2025-07-13 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('admissions', '0003_merge_0002_add_rejection_reason_0002_initial'),
        ('fee_management', '0008_meritlistentry'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meritlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='meritlist',
            name='AcademicSession',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merit_lists', to='admissions.academicsession'),
        ),
        migrations.AddField(
            model_name='meritlist',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], default='Morning', help_text='Shift for the merit list', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='meritlist',
            unique_together={('program', 'list_number', 'shift')},
        ),
    ]
