# Generated by Django 5.2.3 on 2025-07-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0009_alter_meritlist_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meritlist',
            old_name='total_applicants',
            new_name='total_seats',
        ),
        migrations.AlterField(
            model_name='meritlist',
            name='seccured_seats',
            field=models.PositiveIntegerField(default=0, help_text='Number of seats secured from this merit list'),
        ),
    ]
