# Generated by Django 5.2.3 on 2025-07-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0010_rename_total_applicants_meritlist_total_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterfee',
            name='admission_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semesterfee',
            name='admission_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
