# Generated by Django 5.2.3 on 2025-07-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0011_semesterfee_admission_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meritlistentry',
            name='marks_obtained',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Marks obtained in the qualification used', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='meritlistentry',
            name='passing_year',
            field=models.PositiveIntegerField(blank=True, help_text='Passing year of the qualification used', null=True),
        ),
    ]
