# Generated by Django 5.2.3 on 2025-07-15 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0012_meritlistentry_marks_obtained_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meritlist',
            old_name='AcademicSession',
            new_name='academic_session',
        ),
    ]
