# Generated by Django 5.2.3 on 2025-07-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0013_rename_academicsession_meritlist_academic_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meritlistentry',
            name='status',
            field=models.CharField(choices=[('selected', 'Selected'), ('admitted', 'Admitted')], default='selected', help_text='Current status of the candidate in this merit list', max_length=20),
        ),
    ]
