# Generated by Django 5.2.3 on 2025-07-17 02:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0014_alter_meritlistentry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='meritlist',
            name='valid_until_time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Time until which this merit list is valid'),
        ),
    ]
