# Generated by Django 5.2.3 on 2025-07-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_management', '0015_meritlist_valid_until_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meritlist',
            name='valid_until_time',
        ),
        migrations.AlterField(
            model_name='meritlist',
            name='valid_until',
            field=models.DateTimeField(help_text='Date until which this merit list is valid'),
        ),
    ]
