# Generated by Django 5.2 on 2025-05-21 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the full name of the academic faculty (e.g., Faculty of Engineering).', max_length=100)),
                ('slug', models.SlugField(help_text='A unique, web-friendly identifier for the faculty (e.g., faculty-of-engineering). Automatically generated if left blank.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Provide a brief description of the faculty.')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the full name of the department (e.g., Department of Computer Science).', max_length=100)),
                ('slug', models.SlugField(help_text='A unique, web-friendly identifier for the department (e.g., computer-science). Automatically generated if left blank.', max_length=100, unique=True)),
                ('code', models.CharField(help_text='Enter the short code or abbreviation for the department (e.g., CS).', max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Upload an image to represent the department.', null=True, upload_to='departments/')),
                ('introduction', models.TextField(blank=True, help_text='Provide a brief introductory text for the department page.', null=True)),
                ('details', models.TextField(blank=True, help_text='Provide detailed information about the department, its facilities, etc.', null=True)),
                ('faculty', models.ForeignKey(help_text='Select the faculty that this department belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.faculty')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the full name of the academic program (e.g., Bachelor of Science in Computer Science).', max_length=100)),
                ('degree_type', models.CharField(help_text='e.g., PhD, MPhil, BS. Enter the type of degree awarded by this program.', max_length=10)),
                ('duration_years', models.IntegerField(help_text='Enter the number of years it typically takes to complete the program.')),
                ('total_semesters', models.PositiveIntegerField(default=8, help_text='Enter the total number of semesters in the program.')),
                ('department', models.ForeignKey(help_text='Select the department that offers this academic program.', on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academics.department')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
            },
        ),
    ]
