# Generated by Django 5.2 on 2025-05-23 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('courses', '0001_initial'),
        ('faculty_staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course_offering',
            field=models.ForeignKey(help_text='Select the course for which attendance is being recorded', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='courses.courseoffering'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(help_text='The teacher who recorded this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty_staff.teacher'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(help_text='Select the student whose attendance is being recorded', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty',
            field=models.ForeignKey(help_text='Select the faculty that this department belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.faculty'),
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(help_text='Select the department that offers this academic program.', on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='academics.department'),
        ),
        migrations.AddField(
            model_name='semester',
            name='academic_session',
            field=models.ForeignKey(help_text='Select the academic session this semester belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='course_offering',
            field=models.ForeignKey(help_text='Select the course offering for which the grade is being recorded', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='courses.courseoffering'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='grade',
            field=models.ForeignKey(help_text='Final grade awarded (automatically calculated based on total marks)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.gradingsystem'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='student',
            field=models.ForeignKey(help_text='Select the student whose grade is being recorded', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'course_offering', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('academic_session', 'semester_number')},
        ),
        migrations.AlterUniqueTogether(
            name='studentgrade',
            unique_together={('student', 'course_offering')},
        ),
    ]
