# Generated by Django 5.2 on 2025-06-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='session',
            field=models.ForeignKey(help_text='Select the academic session this semester belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='admissions.academicsession'),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('program', 'number', 'session')},
        ),
    ]
