# Generated by Django 5.2 on 2025-05-25 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course_offering',
            field=models.ForeignKey(help_text='Select the course for which attendance is being recorded', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='courses.courseoffering'),
        ),
    ]
