# Generated by Django 5.2 on 2025-05-23 17:34

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('admissions', '0002_alter_academicsession_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='academic_session',
            field=models.ForeignKey(help_text='Select the academic session this semester belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='admissions.academicsession'),
        ),
        migrations.AddField(
            model_name='program',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, help_text='Enter the year when this program ended (leave blank if still active)', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Check this if this program is currently active'),
        ),
        migrations.AddField(
            model_name='program',
            name='start_year',
            field=models.PositiveIntegerField(default=1, help_text='Enter the year when this program started'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='classes_start',
            field=models.DateField(help_text='Select the date when classes begin'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='final_term_end',
            field=models.DateField(help_text='Select the end date of final examinations'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='final_term_start',
            field=models.DateField(help_text='Select the start date of final examinations'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='mid_term_end',
            field=models.DateField(help_text='Select the end date of mid-term examinations'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='mid_term_start',
            field=models.DateField(help_text='Select the start date of mid-term examinations'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='registration_end',
            field=models.DateField(help_text='Select the end date for course registration'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='registration_start',
            field=models.DateField(help_text='Select the start date for course registration'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_number',
            field=models.PositiveIntegerField(help_text='Enter the semester number (1-8)'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_type',
            field=models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring')], help_text='Select whether this is a Fall or Spring semester', max_length=10),
        ),
        migrations.DeleteModel(
            name='AcademicSession',
        ),
    ]
