# Generated by Django 5.2 on 2025-05-25 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('faculty_staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='recorded_by',
            field=models.ForeignKey(help_text='The teacher who recorded this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='faculty_staff.teacher'),
        ),
    ]
