# Generated by Django 5.2 on 2025-05-25 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrade',
            name='grade',
        ),
        migrations.AlterUniqueTogether(
            name='studentgrade',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='course_offering',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='classes_start',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='final_term_end',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='final_term_start',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='mid_term_end',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='mid_term_start',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='registration_end',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='registration_start',
        ),
        migrations.AddField(
            model_name='semester',
            name='description',
            field=models.TextField(blank=True, help_text='Description of what this semester covers'),
        ),
        migrations.AddField(
            model_name='semester',
            name='end_time',
            field=models.DateField(blank=True, help_text='End date of the semester', null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='name',
            field=models.CharField(default=1, help_text="Name of the semester (e.g., 'semester 1', 'semester 2')", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='number',
            field=models.PositiveIntegerField(default=1, help_text='Semester number in the program sequence'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='program',
            field=models.ForeignKey(default=1, help_text='Select the program this semester belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='academics.program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='start_time',
            field=models.DateField(blank=True, help_text='Start date of the semester', null=True),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='GradingSystem',
        ),
        migrations.DeleteModel(
            name='StudentGrade',
        ),
    ]
