# Generated by Django 5.2 on 2025-05-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_studentgrade_grade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['program', 'number'], 'verbose_name': 'Semester', 'verbose_name_plural': 'Semesters'},
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('program', 'number')},
        ),
        migrations.AlterField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this semester is currently active'),
        ),
        migrations.RemoveField(
            model_name='semester',
            name='academic_session',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='semester_number',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='semester_type',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='updated_at',
        ),
    ]
